module.exports = {
    STORE_KEY: 'a56z0fzrNpl^2',
    screen :'',
    time : 0,
    BASE_URL: 'http://139.59.76.223/diskuss/api/',
    home :'home',
    Signin :'Signin',
    Signup :'Signup',
    guid:'',
    muid:'',
    module:'',
    youtubekey:'AIzaSyCkk0Mc6Hha2LUn3NHubv0LLSiumoPVhWs',
    is_yt:0,
    pname:'',
    pimage:'',
    sub:[],
    dimage:'',
    doctor_id:'',
    check_fav:'',
    mycountry:'',
    firebaseToken:'',
    searchLocation:'',
    searchLongitude:'',
    searchLatiude:'',
    doctor_image:'',
    round :'',
    did:'',
    currency:'',
    dollar:'',
    mylong:'',
    mylat:'',
    histoty:[],
    cityid:'',
    all:[],

    searchLocations:'',
    searchLongitudes:'',
    searchLatiudes:'',
    appointment_details:[],
    ambulance:'',
    aid:'',
    emer:'',
    lab_id:'',
    equipment:[],
    newsWhich:'',
    low:0,
    high:0,
    appply : 0,
    onlinetype:'',
    department:'',
    referral:'',
    depart:[],
    newsImage:'',
    newsTitle:'',
    front_main :'front_main',
    industry :'',
    categoryID : '',
    array :[],
    userID:'1',
    profile :'',
    rentPurchase:'',
    location:'',
    doctor_condition:'online',
    token: '',
    session:'',
    productname : '',
    username: '',
    gender: '',
    email: '',
    password: '',
    otps: '',
    nurse :'',
    lab:[],
    labid:'',
    bookingflag:'',
    bookingid:"",
    myid:'',
    mybookingid:'',
    another:'33',
    anothername:'ee',
    bookingstatus:'',
    chatstatus:'',


    nurseArray:[],
    serviceid :'',
    dob: '',
    lat:'',
    long:'',
    appointmentArray :[],
    speciality :'',
    surgries:[],
    illness:[],
    allergies:[],
    selectedAddress:[],
    date:'',
    time:'',
    imgid:'',
    equipmentfor:'',
    labdetail:[],
    type:'',
    package_id:'',
    problem:'',
    searchSpeciality:'',
    medicalEquipment:[],
    shipTime:'',
    imagePath:'',


    couponCode:'',
    couponid:'',
    baseAmount :'',
    discount:'',
    location:'',
    adult:'',
    child:'',
    senior:'',




    related:'',
    productid: '',
    cartId :'',
    myid :'',
    video:'',
    newsid :'',
    derive_category :'derive_category',
    derive_detail_category : 'derive_detail_category',
    info_number :'',
    info_email : '',
    mainid : '',
    user_id:'0',
    matchid:'',
    anotherid:'66',
    mystatus:'Offline',
    dervie_detail_of_product : 'dervie_detail_of_product',
    userInfo :[],
    myname :'varun',
    apply_to:'',
    km:'',
    mymobile :'',
    mymember:[],
    stateid:'',
    is_refer_verify:'0',
    airportLocation:'',
    blog:[],
    toLocation:'',
    price:'',
    referal :'',
    deviceToken:'',
    apply_to:'',
    referral_code_other:'',
    groupName :'',
    groupId :'',
    groupImage:'',
    profileImage:'',
    editGroup:'',
    myemail :'varun.singhal78@gmail.com',
    myusername:'',
    mymobile :'',
    is_refer_verify:'',
    referral_code :'',
    voip:'',
    referal_user_id:'',
    code:'',


    name:'',
    email:'',
    mobile:'',
    address:'',
    city:'',
    state:'',
    password:'',
    mytype:'',
    package:[],
    booking:[],


    otps :'',
    fmobile :'',
    isScreen :'',
    isScreen :'',
    type :'',
    keyword:'',
    author_id :'',
    author :'',
    comment_id:'',
    post_id:'',
    wallets:'',
    anotherUsername:'',
    commentFlagId:'',
    need_help:'need_help',
    onlinename:'',
    onlinegender:'',
    onlinedob:'',
    onlineaddress:'',
    onlinearea:'',
    onlinecity:'',
    onlineMember:[],
    hid:'',
    bookingtype:'',
    heavy:'AvenirLTStd-Heavy',
    roman:'AvenirLTStd-Roman',
    medium:'AvenirLTStd-Medium',
    mytypes:'',
    listofimages:"",
    hids:'',
    cab:[],
    aid:'',
    flight:'',
    report:'',

    airportLongitude:'',
    airportLatiude:'',
    airid:'',
    myi:'',


    travellerusername:'',
    travelleremail:'',
    travellermobile:'',
    travellergender:'',
    local:'',
    issue:[],



    COLOR: {
        ORANGE: '#C50',
        DARKBLUE: '#0F3274',
        LIGHTBLUE: '#6EA8DA',
        DARKGRAY: '#999',
    },
};
